identifier: l6aab95czct9we14
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: C:\Users\archi\repo\my-blog
distFolder: dist/my-blog
outDir: C:\Users\archi\repo\my-blog\dist\static
handle404: ''
allowErrorCollect: false
